"""Split images into additional table

Revision ID: b387f135f97b
Revises: a28b9ed2c39e
Create Date: 2024-04-04 16:20:17.720606

"""

from typing import Sequence, Union

import fastapi_storages
from alembic import op
import sqlalchemy as sa

from config import product_img_storage

# revision identifiers, used by Alembic.
revision: str = "b387f135f97b"
down_revision: Union[str, None] = "a28b9ed2c39e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "path",
            fastapi_storages.integrations.sqlalchemy.FileType(
                storage=product_img_storage
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("category", "image")
    op.drop_column("product", "image")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "category", sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_table("image")
    # ### end Alembic commands ###
