"""Change rating_avg to rating

Revision ID: 733d162d3e7b
Revises: 52a166e44ee7
Create Date: 2024-03-25 21:37:03.236180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733d162d3e7b'
down_revision: Union[str, None] = '52a166e44ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('rating', sa.Float(), nullable=True))
    op.drop_column('product', 'rating_avg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('rating_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('product', 'rating')
    # ### end Alembic commands ###
