"""Modify Product Image

Revision ID: d5889cc4ad5c
Revises: 7f7d53bae822
Create Date: 2024-03-25 18:29:51.357453

"""
from typing import Sequence, Union

from fastapi_storages.integrations.sqlalchemy import FileType
from alembic import op
import sqlalchemy as sa

from products.models import img_storage

# revision identifiers, used by Alembic.
revision: str = 'd5889cc4ad5c'
down_revision: Union[str, None] = '7f7d53bae822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', FileType(storage=img_storage), nullable=True))
    op.drop_column('product', 'img_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
